Improve compatibility, switch to typescript, etc
vkurchatkin/koa-connect pull request #6
Opened 2017-01-13 03:05 UTC by cyrilluce

* use ctx.respond to skip koa2 finalize render
* use response#close/finish event to detect middleware finished
* use typescript to compile compatible code with node 4
* examples and tests bugfix: koa2 middleware should return next() while without async keyword

2017-01-17 17:38 UTC, lourd requested changes
Thanks for this @cyrilluce. It's a much more comprehensive shim than what we've had so far, and fixes a few bugs. Nice work.

I take it you've been using this code or something very similar to it in your projects?

A couple questions:
- Do we need to use typescript? I'm not convinced the couple features that are being used that aren't supported in Node v4 are worth the transpilation step and related code overhead. It's just the one `async` and `await` and the spread operator, no?
- What's with the commented out `markHandled` and `hasHandled` functions and variables? If they're not part of this proposed version please remove them.

2017-01-17 17:38 UTC, lourd commented on ts/index.ts
> +  let dummyRes = Object.create(res);
`const` here, not `let`

2017-01-17 17:38 UTC, lourd commented on ts/index.ts
> +  let res = koaCtx.res;
`const`, not `let`

2017-01-17 17:38 UTC, lourd commented on ts/index.ts
> +    let args = [
`const` here for `args`

2017-01-17 17:38 UTC, lourd commented on ts/index.ts
> +        res.statusCode = 200;
What if `writeHead` set the status code to `404` intentionally? Is this a valid assumption? Does it make a difference if it comes before calling the corresponding method on `res`?

Maybe we replace `404` with our own number or flag, check if it's equal to that, set it accordingly?

2017-01-17 17:45 UTC, vkurchatkin commented
@cyrilluce you've changed package name and package author. I think it's a good indicator that this shouldn't be merged

2017-01-17 17:48 UTC, lourd commented
Right, forgot to mention that, thanks @vkurchatkin. Please change the repository url, package name, author, and version number back to what they were before @cyrilluce.

2017-01-17 19:05 UTC, cyrilluce commented
@lourd 
Thank you for encourage me to create pull request. at beginning I just want build next version, and change code very easy, so there are some big change(like typescript).
1. Yes, use typescript is to simplify the source code, and generate node v4 compatible build. Write compatible code is painful. I'm sorry for the lazy job. lol
2. You can remove markHandled and hasHandled
Maybe we can spend some time rewrite to compatible with node v4 without typescript.

@vkurchatkin I'm sorry for forgotten to restore `package.json`

2017-01-17 19:17 UTC, cyrilluce commented on ts/index.ts
> +        res.statusCode = 200;
You are right, in past I didn't find proper simple way to avoid that. It's bugfix for directly res.end(...) resulting 404.

2017-01-17 21:42 UTC, lourd commented
You're welcome! Thanks for making it 😄 

If you push new commits to the master branch on your fork GitHub will automatically update the pull request.

Totally understand wanting to use the newer JS features. Can't wait till async-await, spread, rest, all that good stuff is in Node LTS.

It's only a couple small changes to be v4 compatible:
- Change the body of `koaConnect` to not use async-await:

```js
return (ctx, next) => {
  ctx.respond = false;
  return handler(ctx, connectMiddleware)
    .then(goNext => {
      if (goNext) {
        ctx.respond = true;
        return next();
      }
    })
    .catch(err => {
      ctx.respond = true
      throw err
    })
}
```

- Change `connectMiddleware(...args)` to `connectMiddleware.apply(null, args)`
- Change 
    ```js
    dummyRes[name] = (...args) => {
      res[name](...args) 
    }
    ``` 

    to 
    ```js
    dummyRes[name] = function() { 
      res[name].apply(null, arguments) 
    }
    ```

2017-01-17 21:51 UTC, lourd commented on ts/index.ts
> +        res.statusCode = 200;
Ok. We should write a test case or two for this so we understand what behavior we want. Do you think this behavior needs to be included in this PR, or can it be separate?

2017-01-20 13:52 UTC, cyrilluce commented
@lourd updated.
But I got another issue, and don't know how to deal with.

In webpack-dev-middleware, there have codes:
> // Express automatically sets the statusCode to 200, but not all servers do (Koa).
> res.statusCode = res.statusCode || 200;

And my 404 issue improve will cause failure, or we should force initial set it to 200? or even set it to `undefined`? (actually we don't compatible with `Express`, but just `connect`)

2018-02-14 16:26 UTC, lourd commented
Closing this PR since it's gone a year without activity. Feel free to re-open if you're still interested

2018-02-14 16:26 UTC, closed without merging